-- Supabase schema for SciNet / ResearchOS
-- Focuses on dynamic experiment data capture and PDF embeddings

-- Extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";
create extension if not exists vector;

-- Utility trigger to keep updated_at columns fresh.
create or replace function public.set_current_timestamp_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Projects represent independent research contexts.
create table if not exists projects (
    id uuid primary key default gen_random_uuid(),
    owner_id uuid references auth.users(id) on delete set null,
    name text not null,
    description text,
    status text not null default 'draft',
    hypothesis text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger set_projects_updated_at
before update on projects
for each row execute procedure public.set_current_timestamp_updated_at();

-- Project-specific variables (inputs) defined by the user or suggested by AI.
create table if not exists project_variables (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references projects(id) on delete cascade,
    slug text not null,
    name text not null,
    data_type text not null check (data_type in ('number', 'categorical', 'boolean', 'text', 'json')),
    unit text,
    description text,
    allowed_values jsonb default '{}'::jsonb,
    default_value jsonb,
    required boolean not null default false,
    created_at timestamptz not null default now()
);

create unique index if not exists project_variables_project_slug_idx
    on project_variables (project_id, slug);

-- Project-specific metrics (outputs) defined by the user or suggested by AI.
create table if not exists project_metrics (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references projects(id) on delete cascade,
    slug text not null,
    name text not null,
    data_type text not null check (data_type in ('number', 'categorical', 'boolean', 'text', 'json')),
    unit text,
    description text,
    calculation_notes text,
    created_at timestamptz not null default now()
);

create unique index if not exists project_metrics_project_slug_idx
    on project_metrics (project_id, slug);

-- Experiments capture a single iteration of the research loop.
-- Inputs and outputs are stored as JSONB keyed by the associated variable/metric slug.
create table if not exists experiment_runs (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references projects(id) on delete cascade,
    run_number integer generated by default as identity,
    title text,
    notes text,
    state text not null default 'proposed',
    inputs jsonb not null default '{}'::jsonb,
    outputs jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (project_id, run_number)
);

create index if not exists experiment_runs_project_idx on experiment_runs(project_id);
create index if not exists experiment_runs_inputs_gin_idx on experiment_runs using gin (inputs jsonb_path_ops);
create index if not exists experiment_runs_outputs_gin_idx on experiment_runs using gin (outputs jsonb_path_ops);

create trigger set_experiment_runs_updated_at
before update on experiment_runs
for each row execute procedure public.set_current_timestamp_updated_at();

-- Optional normalized table for per-variable search/aggregation without unpacking JSON on every query.
create table if not exists experiment_variables_flat (
    id bigserial primary key,
    experiment_id uuid not null references experiment_runs(id) on delete cascade,
    project_id uuid not null references projects(id) on delete cascade,
    variable_slug text not null,
    value jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists experiment_variables_flat_lookup_idx
    on experiment_variables_flat (project_id, variable_slug);
create index if not exists experiment_variables_flat_value_gin_idx
    on experiment_variables_flat using gin (value jsonb_path_ops);

-- Optional normalized table for per-metric search/aggregation.
create table if not exists experiment_metrics_flat (
    id bigserial primary key,
    experiment_id uuid not null references experiment_runs(id) on delete cascade,
    project_id uuid not null references projects(id) on delete cascade,
    metric_slug text not null,
    value jsonb not null,
    created_at timestamptz not null default now()
);

create index if not exists experiment_metrics_flat_lookup_idx
    on experiment_metrics_flat (project_id, metric_slug);
create index if not exists experiment_metrics_flat_value_gin_idx
    on experiment_metrics_flat using gin (value jsonb_path_ops);

-- Knowledge base: PDF sources and embedded chunks for RAG.
create table if not exists project_documents (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references projects(id) on delete cascade,
    title text,
    source_url text,
    storage_path text not null,
    token_count integer,
    checksum text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists project_documents_project_idx on project_documents(project_id);

-- Chunked embeddings linked to documents for semantic search.
create table if not exists document_chunks (
    id bigserial primary key,
    project_id uuid not null references projects(id) on delete cascade,
    document_id uuid not null references project_documents(id) on delete cascade,
    chunk_index integer not null,
    content text not null,
    token_count integer,
    embedding vector(1536) not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (document_id, chunk_index)
);

create index if not exists document_chunks_project_idx on document_chunks(project_id);
create index if not exists document_chunks_embedding_idx
    on document_chunks using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- AI-generated artifacts: prompts, hypotheses, and analyses linked to experiments.
create table if not exists ai_artifacts (
    id uuid primary key default gen_random_uuid(),
    project_id uuid not null references projects(id) on delete cascade,
    experiment_id uuid references experiment_runs(id) on delete cascade,
    kind text not null check (kind in ('variable_suggestion', 'metric_suggestion', 'experiment_plan', 'analysis', 'manuscript_section')),
    content jsonb not null,
    model text,
    created_at timestamptz not null default now()
);

create index if not exists ai_artifacts_project_idx on ai_artifacts(project_id);
create index if not exists ai_artifacts_experiment_idx on ai_artifacts(experiment_id);

-- Simple view to expose flattened variable/metric lookups per experiment for analytics dashboards.
create or replace view experiment_data_wide as
select
    er.id as experiment_id,
    er.project_id,
    er.run_number,
    er.state,
    er.created_at,
    er.updated_at,
    er.inputs,
    er.outputs
from experiment_runs er;
